import AdminHello from "./AdminHello"

const Admin = () => {
    return (
        <main className="admin">

            <AdminHello />

            <h2>Admin</h2>
  
            <p>Ex, velit? Architecto, qui. Aut est quia, provident dolor ab iure pariatur itaque ducimus quaerat repudiandae recusandae nesciunt laudantium, vitae enim natus placeat vero id voluptatem unde saepe, voluptatum possimus. Veritatis, aperiam eligendi. Ducimus, beatae dolorum illum impedit distinctio quisquam praesentium neque quaerat nam cupiditate exercitationem ipsa at perspiciatis temporibus fugit laudantium facere recusandae error nobis natus velit voluptate sunt. Atque obcaecati ex repudiandae debitis soluta consequatur sunt fugiat consectetur sequi, voluptate dignissimos eaque dolorem, magni voluptas repellendus eum molestiae distinctio maxime. Eaque dolore quod quibusdam obcaecati hic eos excepturi in libero id. Voluptatum possimus ut reprehenderit officiis inventore excepturi?</p>
            <p>Eius, esse maxime. Praesentium magnam delectus minima labore fugit harum consectetur, sit eos saepe minus perspiciatis maxime. Libero esse debitis temporibus qui minus voluptatum odio ea maiores adipisci nulla, fuga molestiae aliquam ducimus ut labore sint. Impedit quae odit dolore. Accusantium nulla aspernatur doloribus eveniet qui, nam ratione. Dolore quasi, numquam illum voluptatum architecto ipsam magnam earum nisi voluptates voluptas repellat quia ab commodi consequatur officia atque hic quos. Aspernatur nemo, sequi praesentium deleniti sapiente distinctio hic mollitia est porro eos dolor aliquam illum. Distinctio eius architecto numquam laboriosam nisi tenetur et voluptatibus dolorem sit unde culpa, quo eos officia!</p>
            <p>Magni, est illum. Quis eum commodi aspernatur nulla dolor laborum tempore sunt explicabo impedit qui laboriosam vel dolores repellendus quaerat ipsam quae hic, quas ea in quo! Debitis non fugit repellat! Quod eligendi nam quasi, minima at explicabo aut tenetur eos voluptatibus, eum optio aliquid. Sit, ipsa? Laudantium dolorem optio laboriosam natus omnis et error, officia perspiciatis. Quisquam numquam cumque optio deserunt? Numquam, cupiditate? Obcaecati in labore dolorum magnam, aspernatur ipsum cupiditate delectus, quas, dicta necessitatibus reprehenderit ut esse similique itaque corrupti ab suscipit impedit veritatis tenetur molestiae nemo. Eum excepturi nostrum distinctio reiciendis voluptatem maxime hic, itaque dolore consequatur.</p>
            <p>Repudiandae temporibus excepturi fuga commodi, natus consectetur et animi veniam quisquam quo hic possimus laudantium modi magnam velit itaque eos. Officia dignissimos odit maxime accusamus corrupti ullam ab inventore, perferendis blanditiis delectus aut vel voluptatibus. Id praesentium doloremque delectus reprehenderit modi iure architecto ratione, assumenda, odio labore debitis autem numquam ad. Suscipit doloribus sequi recusandae! Corporis, ipsam. Ipsa debitis, consectetur autem sunt necessitatibus harum consequuntur ut, repellendus aspernatur maiores, omnis cupiditate fugiat consequatur commodi ullam! Natus, nulla adipisci tenetur culpa voluptate nam illo sapiente sint est, voluptas reiciendis quisquam, nemo temporibus in officia molestias architecto eligendi. Sit laudantium architecto eligendi.</p>
 
            <p>Quaerat dicta illo blanditiis, sit ratione laboriosam consectetur corporis quia quam voluptatibus numquam ex veniam. Quo eius eos consequuntur eum minima expedita consectetur? Voluptate nulla sapiente laborum sunt accusantium officia dolorum vero officiis sequi? Ipsum, nisi corrupti earum neque alias doloribus nemo consectetur temporibus obcaecati odit recusandae minima? Veritatis provident repudiandae nostrum! Culpa, quibusdam suscipit perferendis dolore alias nihil debitis repellat? Vero beatae a quasi deserunt accusamus voluptate quisquam fuga perferendis eum adipisci ab quam maiores laborum impedit aspernatur dolorum, corporis expedita corrupti harum quaerat sunt, repudiandae officia, architecto nobis? Inventore magni sed totam numquam enim dolores perspiciatis excepturi labore.</p>
            <p>Quidem consectetur praesentium sint assumenda, sequi, perferendis sapiente, veritatis labore expedita nihil aut cum inventore. Aperiam ratione sit dignissimos beatae excepturi animi cupiditate velit? Totam doloremque unde cum, laudantium suscipit maxime quod pariatur inventore quaerat cupiditate, ullam qui minima ipsam velit repellat nam ipsum. Repellendus, neque! Eveniet eos molestias ducimus enim exercitationem ut. Pariatur, rem, omnis quo fugit illum voluptatibus inventore vero incidunt dolorum molestiae perferendis veritatis reiciendis necessitatibus unde nam explicabo? Doloribus aut, ipsum repellat sit eum corporis iste sapiente nulla aperiam delectus qui voluptates ad suscipit itaque. Rerum modi fugiat iusto et qui iure sunt reprehenderit! Ad, alias?</p>
            <p>Neque minima recusandae omnis nihil, architecto labore voluptates dicta eaque harum pariatur expedita impedit libero unde inventore nostrum repellendus et veritatis ea, nulla earum sit laudantium blanditiis magnam? Esse laudantium, iste modi sint maxime asperiores excepturi velit commodi repellendus numquam quam pariatur, atque natus? Eos quis nemo ipsum velit, iste dolores reiciendis! Voluptatibus aperiam distinctio neque perspiciatis commodi vel officia animi consectetur veritatis expedita libero quos mollitia, dolor fuga in eos tempora qui quaerat illum alias tenetur eius culpa enim facilis? Voluptatem, a! Fugiat nemo pariatur repellendus earum aspernatur maxime magni excepturi? Dolorum ex officiis maxime nesciunt eos laborum ducimus.</p>
            <p>Tempora, repudiandae illum rerum nemo expedita ex ullam, tempore vero quaerat exercitationem velit laudantium sequi reprehenderit adipisci quia ipsa? Ut nisi maiores dignissimos soluta aspernatur possimus dolorum, atque enim unde deleniti nemo alias, iste corrupti dolore explicabo magni sunt magnam repellat molestiae quis! Eveniet modi maxime ab harum. Repudiandae asperiores consectetur saepe est. Praesentium nesciunt omnis eaque tempora sapiente nostrum ea impedit autem quam, laboriosam at provident quaerat perspiciatis, libero voluptate inventore doloremque ad ipsum distinctio quia? Repellendus natus iusto accusantium blanditiis cupiditate quisquam totam assumenda. Ex suscipit esse quia! Commodi qui repellendus voluptates, magni accusantium adipisci aperiam nobis molestias.</p>
            <p>Voluptatum dignissimos distinctio iste error dolorum incidunt facilis facere quod ducimus mollitia, magni itaque fugiat eius eligendi sit, ab possimus eveniet provident? Adipisci eveniet sed ex maxime? Id, quos consequatur. Voluptatum perferendis, beatae velit illo laborum sed asperiores eum quae et molestias aperiam quia quos in! Officiis perferendis laborum saepe excepturi maxime cumque tempora enim quae quasi ea quisquam repudiandae aliquam eos in, atque aut nobis, odio voluptates. Ex numquam tempore doloremque illum in dolores? Placeat sint eligendi quis alias ipsam necessitatibus dolore magni voluptatibus amet, quas quibusdam natus dolorem, nesciunt, inventore consequatur at corrupti odio porro expedita minima ad.</p>
            <p>Itaque similique doloribus, rem adipisci vitae voluptate veritatis exercitationem ab obcaecati est officiis suscipit amet molestiae cum ipsam. Quaerat modi, quidem dolorem, hic necessitatibus quam expedita quis similique cum assumenda reprehenderit rem tenetur odit consequuntur sequi illum! Porro harum earum labore laborum, facere magni magnam ipsa officia rerum neque eveniet, eum expedita, quos error beatae molestias fugit eligendi provident rem? Quas modi beatae saepe fugiat culpa iure suscipit, ipsum voluptas expedita, natus maxime nisi iste quisquam, quia aspernatur odio distinctio omnis incidunt deserunt molestias earum labore odit! Maxime, molestiae doloremque pariatur mollitia laudantium dolores eos rerum quos, quam tempore aliquam.</p>
            <p>Quam id vero vel debitis! Sunt, obcaecati praesentium est perferendis inventore at consectetur impedit tempora omnis qui suscipit ullam consequatur natus numquam eos id aspernatur ipsam vero sit ut? Placeat tenetur dolorum ex neque maxime nemo maiores distinctio nam, nobis molestiae quas saepe molestias? Itaque cupiditate similique officiis ut voluptatum repellendus alias illo ea. Asperiores autem incidunt sapiente architecto earum necessitatibus libero doloribus, similique soluta modi fugiat quam ipsam maxime perspiciatis. Perferendis vel unde debitis commodi voluptatum, ducimus non veniam, suscipit aspernatur, alias sit tempora maxime dicta! Cumque neque atque quisquam, quae accusamus error ullam impedit distinctio quasi. Ab, asperiores.</p>
            <p>Quos accusantium pariatur officia quod facere soluta consectetur ipsa dolores excepturi temporibus expedita id quas atque veritatis qui veniam quaerat nam quibusdam ex esse, libero totam nulla fugit? Et ipsa ad quae facilis obcaecati! Porro iusto labore delectus autem similique illum est necessitatibus laboriosam nisi non sit minima facere veniam consectetur repudiandae nam id blanditiis mollitia numquam, maiores perferendis? Perspiciatis et minima omnis facilis labore aspernatur iure quidem voluptatibus quod rerum recusandae nisi tempore, porro aliquid eius dolores itaque doloribus, reiciendis delectus nulla! Esse eveniet voluptatibus at dolorem commodi molestias consectetur repudiandae omnis. Quae nisi perspiciatis voluptate, praesentium minus enim.</p>
            <p>Perspiciatis accusantium quo optio repudiandae dolorem repellat, est laborum adipisci quas ipsum ad explicabo dolorum iusto quos, similique numquam iure? Perspiciatis perferendis architecto, fugit, veritatis, voluptatum eos officiis autem distinctio delectus cupiditate et ea quas laborum necessitatibus fuga voluptate! Nihil, sapiente? Eaque libero exercitationem cumque porro, dolorum ab deserunt eius corporis dicta magni impedit incidunt nam, laudantium tenetur tempora explicabo consequuntur deleniti possimus accusantium ad non atque dolorem officiis. Voluptatibus cum neque alias eveniet? At asperiores molestias impedit illo nam, architecto magnam perspiciatis neque eaque fugiat tempora, sequi natus laboriosam totam, unde eum repellendus rerum odio. Sequi, asperiores commodi. Expedita.</p>
            <p>Esse ad voluptatibus libero officiis optio, beatae accusamus dolorem consequatur consectetur qui unde in assumenda! Eius, veritatis. Reiciendis hic sed placeat cumque dolor maxime eius esse molestias dolorem, sequi voluptatum, aliquam sapiente debitis. Hic labore dolorum deleniti quo soluta, laudantium aliquid sed! Totam laborum aspernatur nulla perferendis ut assumenda numquam. Maiores sunt consectetur deserunt dolorum dignissimos quidem cupiditate pariatur accusantium saepe, ipsa corporis voluptatibus perspiciatis, alias nostrum minus molestias suscipit esse? Voluptatem id quae magni ipsum aperiam iure, aliquam saepe maxime inventore adipisci aliquid perspiciatis ea quas? Dolorum id mollitia, aperiam quos magnam perferendis officia doloremque dolores, placeat ipsa ab?</p>
            <p>Expedita veniam, earum mollitia error iste adipisci nemo asperiores veritatis velit facilis amet provident accusantium commodi quasi nisi, fuga sed, dicta deserunt minima dolore eos corrupti! Vitae error, accusamus modi facilis omnis atque repellendus inventore id sed mollitia quidem corrupti quibusdam labore ea quia iste voluptate sit repudiandae quod aliquid doloremque eum nesciunt possimus eveniet! Nisi itaque ab quibusdam sunt fugiat praesentium ipsum, doloribus consequuntur harum neque? Debitis placeat, unde aspernatur laborum excepturi eum sapiente consequatur necessitatibus? Nulla sequi atque placeat unde illum accusamus ipsam, reiciendis tenetur delectus ducimus laborum cumque quia sit laboriosam quibusdam necessitatibus, voluptatem fuga id itaque!</p>
            <p>Provident optio vitae alias amet mollitia, delectus dolor deleniti veritatis hic quam atque? Rerum nulla eligendi obcaecati nam et a ad illum aspernatur unde consequuntur saepe provident non id commodi nesciunt neque possimus atque laborum modi dolores, quia ex. Doloribus quis illum natus nam ut, expedita tempore commodi eius, ex, molestiae architecto odio excepturi dolore consectetur veritatis voluptas illo. Cum eius sunt vel illum odit optio velit qui reprehenderit nulla! Amet maxime eos saepe ex beatae consectetur facilis id, libero illum cumque non explicabo sunt laudantium soluta quasi sequi voluptatem commodi. Odit tempore saepe, debitis nihil accusamus possimus esse ut.</p>


        </main>
    )
}
export default Admin